name: Node.js apps

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install/Build all
        run: |
          npm run build:apps

      - name: home.app.weather Tests
        working-directory: ./apps/home.app.weather
        run: |
          npm run lint
          npm run test

      - name: home.app.host Tests
        working-directory: ./apps/home.app.host
        run: |
          npm run test